In [1]:
# -----------------------------------------------------------------
# --- 1. GİRİŞ: KURULUM VE IMPORT ETME ---
# -----------------------------------------------------------------

import numpy as np

import time 

# Python list ile toplama
python_list = list(range(1000000))
start = time.time()
toplam = sum(python_list)
print(f"Python list: {time.time() - start:.6f} saniye")

Python list: 0.018550 saniye


In [2]:
# NumPy array ile toplama
numpy_array = np.array(range(1000000))
start = time.time()
toplam = np.sum(numpy_array)
print(f"NumPy array: {time.time() - start:.6f} saniye")

NumPy array: 0.006030 saniye


In [3]:
print("\nNumPy daha hızlı!")
import numpy as np
print(f"NumPy Versiyonu: {np.__version__}")


NumPy daha hızlı!
NumPy Versiyonu: 1.26.4


In [4]:
# -----------------------------------------------------------------
# --- 2. TEMEL ARRAY OLUŞTURMA ---
# -----------------------------------------------------------------

print("\n" + "="*30 + "\n2. TEMEL ARRAY OLUŞTURMA\n" + "="*30)

# Python listesinden 1D Array (Vektör)
arr1 = np.array([1,2,3,4,5])
print(f"1D Array:\n{arr1}")



2. TEMEL ARRAY OLUŞTURMA
1D Array:
[1 2 3 4 5]


In [5]:
# Python iç içe listesinden 2D Array (Matris)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n{arr2}")


2D Array:
[[1 2 3]
 [4 5 6]]


In [6]:
# `np.arange(start, stop, step)`
# Belirtilen aralıkta dizi oluşturur (stop dahil değil)
arr_arange = np.arange(0,10,2)
print(f"arange(0, 10, 2):\n{arr_arange}")


arange(0, 10, 2):
[0 2 4 6 8]


In [7]:
# `np.zeros(shape)`
# Belirtilen boyutta sıfırlardan oluşan array
arr_zeros = np.zeros((2, 3)) # 2 satır, 3 sütun
print(f"zeros((2, 3)):\n{arr_zeros}")
;

zeros((2, 3)):
[[0. 0. 0.]
 [0. 0. 0.]]


''

In [8]:
# `np.ones(shape)`
# Belirtilen boyutta birlerden oluşan array
arr_ones = np.ones((3, 2))
print(f"ones((3, 2)):\n{arr_ones}")


ones((3, 2)):
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
# `np.linspace(start, stop, num)`
# Başlangıç ve bitiş arasında (ikisi de dahil) 'num' adet eşit aralıklı sayı
arr_lin = np.linspace(0, 1, 5) # 0, 0.25, 0.5, 0.75, 1.0
print(f"linspace(0, 1, 5):\n{arr_lin}")


linspace(0, 1, 5):
[0.   0.25 0.5  0.75 1.  ]


In [10]:
# `np.logspace(start, stop, num)`
# 10^start ve 10^stop arasında 'num' adet logaritmik aralıklı sayı
arr_log = np.logspace(0, 2, 3) # 10^0, 10^1, 10^2 -> [1., 10., 100.]
print(f"logspace(0, 2, 3):\n{arr_log}")


logspace(0, 2, 3):
[  1.  10. 100.]


In [11]:
# `np.full(shape, fill_value)`
# Belirtilen boyutta ve belirtilen değerle doldurulmuş array
arr_full = np.full((2, 4), 7)
print(f"full((2, 4), 7):\n{arr_full}")


full((2, 4), 7):
[[7 7 7 7]
 [7 7 7 7]]


In [12]:
# `np.eye(N)`
# N x N boyutlu birim matris (Identity matrix)
arr_eye = np.eye(3)
print(f"eye(3):\n{arr_eye}")


eye(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# -----------------------------------------------------------------
# --- 3. RASTGELE SAYI ÜRETİMİ (np.random) ---
# -----------------------------------------------------------------
print("\n" + "="*30 + "\n3. RASTGELE SAYI ÜRETİMİ\n" + "="*30)
# Sonuçların tekrarlanabilir olması için 'seed' (tohum) ayarlanır
np.random.seed(42) # 42, sektörde bir gelenektir :)

# `np.random.rand(d0, d1, ...)`
# 0 ile 1 arasında uniform dağılımlı sayılar
arr_rand = np.random.rand(2, 3)
print(f"rand(2, 3) (0-1 arası):\n{arr_rand}")



3. RASTGELE SAYI ÜRETİMİ
rand(2, 3) (0-1 arası):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


In [14]:
# `np.random.randn(d0, d1, ...)`
# Ortalama 0, Standart Sapma 1 olan normal (gaussian) dağılım
arr_randn = np.random.randn(2, 3)
print(f"randn(2, 3) (Normal dağılım):\n{arr_randn}")


randn(2, 3) (Normal dağılım):
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]


In [15]:
# `np.random.randint(low, high, size)`
# 'low' (dahil) ile 'high' (hariç) arası rastgele tamsayılar
arr_randint = np.random.randint(10, 20, size=(3, 4))
print(f"randint(10, 20, size=(3, 4)):\n{arr_randint}")


randint(10, 20, size=(3, 4)):
[[19 15 18 10]
 [19 12 16 13]
 [18 12 14 12]]


In [16]:
# `np.random.shuffle(array)`
# Array'i yerinde (in-place) karıştırır. Geriye bir şey döndürmez.
a = np.arange(10)
print(f"Shuffle öncesi: {a}")
np.random.shuffle(a)
print(f"Shuffle sonrası: {a}")


Shuffle öncesi: [0 1 2 3 4 5 6 7 8 9]
Shuffle sonrası: [8 2 5 7 3 1 9 0 4 6]


In [17]:
# `np.random.choice(array, size, replace=True)`
# Bir array'den rastgele seçim yapar
# `replace=False` -> Bir eleman sadece bir kez seçilebilir
choices = np.random.choice(a, 5, replace=False)
print(f"Rastgele 5 seçim (tekrarsız): {choices}")


Rastgele 5 seçim (tekrarsız): [8 1 5 9 7]


In [18]:
# -----------------------------------------------------------------
# --- 4. ARRAY ÖZELLİKLERİ VE VERİ TİPLERİ ---
# -----------------------------------------------------------------

print("\n" + "="*30 + "\n4. ARRAY ÖZELLİKLERİ VE VERİ TİPLERİ\n" + "="*30)
data = np.random.randint(0, 10, (3, 5))
print(f"Veri:\n{data}")



4. ARRAY ÖZELLİKLERİ VE VERİ TİPLERİ
Veri:
[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]


In [19]:
# `.shape`: Boyut (satır, sütun) -> (3, 5)
print(f"Shape (Boyut): {data.shape}")


Shape (Boyut): (3, 5)


In [20]:
# `.ndim`: Boyut sayısı -> 2
print(f"ndim (Boyut sayısı): {data.ndim}")


ndim (Boyut sayısı): 2


In [21]:
# `.size`: Toplam eleman sayısı -> 15
print(f"size (Toplam eleman): {data.size}")


size (Toplam eleman): 15


In [22]:
# `.dtype`: İçeride tutulan verinin tipi
print(f"dtype (Veri Tipi): {data.dtype}")


dtype (Veri Tipi): int32


In [23]:
# Veri Tipi Belirleme ve Değiştirme
# Oluştururken tipi belirleme (hafıza yönetimi için önemli)
arr_float = np.array([1, 2, 3], dtype=np.float32)
print(f"Float32 Array: {arr_float}, Tipi: {arr_float.dtype}")


Float32 Array: [1. 2. 3.], Tipi: float32


In [24]:
# `.astype()`: Varolan bir array'in tipini değiştirme
arr_int = arr_float.astype(np.int64)
print(f"Int64'e dönüştü: {arr_int}, Tipi: {arr_int.dtype}")


Int64'e dönüştü: [1 2 3], Tipi: int64


In [25]:
# -----------------------------------------------------------------
# --- 5. YENİDEN ŞEKİLLENDİRME (Reshaping) ---
# -----------------------------------------------------------------

print("\n" + "="*30 + "\n5. YENİDEN ŞEKİLLENDİRME\n" + "="*30)
a = np.arange(1, 13) # 12 eleman
print(f"Orijinal 1D Array: {a}")



5. YENİDEN ŞEKİLLENDİRME
Orijinal 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
# `.reshape(yeni_boyut)`
# Toplam eleman sayısı (size) değişmemeli (3*4 = 12)
b = a.reshape(3, 4)
print(f"Reshape (3, 4):\n{b}")


Reshape (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
# `-1` kullanımı: Bilinmeyen boyutu NumPy'ın hesaplamasını sağlar
# 12 elemanlı array'i 2 satırlı yap, sütunu sen hesapla (12/2=6)
c = a.reshape(2, -1)
print(f"Reshape (2, -1):\n{c}")


Reshape (2, -1):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [28]:
# Düzleştirme (Matrisi tekrar vektöre çevirme)
# `.ravel()`: Orijinal verinin bir "görünümünü" (view) döndürür. Hızlıdır.
d = b.ravel()
print(f"ravel() ile düzleştirme: {d}")


ravel() ile düzleştirme: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [29]:
# `.flatten()`: Verinin bir "kopyasını" (copy) döndürür. Daha güvenlidir.
e = b.flatten()
print(f"flatten() ile düzleştirme: {e}")


flatten() ile düzleştirme: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
# -----------------------------------------------------------------
# --- 6. INDEXING VE SLICING (Erişim ve Dilimleme) ---
# -----------------------------------------------------------------

print("\n" + "="*30 + "\n6. INDEXING VE SLICING\n" + "="*30)
# --- 6.1. 1D Array'ler ---
arr1d = np.arange(10, 20)
print(f"\n1D Array: {arr1d}")
print(f"İlk eleman [0]: {arr1d[0]}")
print(f"Son eleman [-1]: {arr1d[-1]}")
print(f"Dilimleme [2:5]: {arr1d[2:5]}") # 2. index'ten 5. (hariç)
print(f"Tersten yazdırma [::-1]: {arr1d[::-1]}")



6. INDEXING VE SLICING

1D Array: [10 11 12 13 14 15 16 17 18 19]
İlk eleman [0]: 10
Son eleman [-1]: 19
Dilimleme [2:5]: [12 13 14]
Tersten yazdırma [::-1]: [19 18 17 16 15 14 13 12 11 10]


In [31]:
# --- 6.2. 2D Array'ler (Matrisler) ---
# Format: `array[satır, sütun]` (En çok kullanılan)
# veya `array[satır][sütun]` (Daha yavaş, önerilmez)
arr2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(f"\n2D Array:\n{arr2d}")



2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [32]:
# Tek eleman (2. satır, 3. sütun -> 60)
print(f"[1, 2] -> {arr2d[1, 2]}")


[1, 2] -> 60


In [33]:
# Tek satır (1. satırın tamamı)
print(f"[0, :] (veya [0]) -> {arr2d[0, :]}")


[0, :] (veya [0]) -> [10 20 30]


In [34]:
# Tek sütun (2. sütunun tamamı)
print(f"[:, 1] -> {arr2d[:, 1]}")


[:, 1] -> [20 50 80]


In [35]:
# Alt matris dilimleme (İlk 2 satır ve son 2 sütun)
# [[20, 30], [50, 60]]
alt_matris = arr2d[0:2, 1:3]
print(f"Alt Matris [0:2, 1:3]:\n{alt_matris}")


Alt Matris [0:2, 1:3]:
[[20 30]
 [50 60]]


In [ ]:
# --- 6.3. Slicing: View vs. Copy (ÇOK ÖNEMLİ!) ---
# NumPy'da dilimleme (slicing) bir KOPYA (copy) oluşturmaz,
# ana verinin bir GÖRÜNÜMÜNÜ (view) döndürür. Bu, hafızadan tasarruf sağlar.
print("\n--- View vs. Copy ---")
alt_gorunum = arr2d[0:2, 0:2]
print(f"Orijinal alt görünüm:\n{alt_gorunum}")


--- View vs. Copy ---
Orijinal alt görünüm:
[[10 20]
 [40 50]]


In [37]:
# Alt görünümde bir değişiklik yapalım
alt_gorunum[0, 0] = 999
print(f"Değiştirilmiş alt görünüm:\n{alt_gorunum}")

Değiştirilmiş alt görünüm:
[[999  20]
 [ 40  50]]


In [38]:
# ANA ARRAY DE DEĞİŞİR!
print(f"DEĞİŞİM SONRASI ANA ARRAY:\n{arr2d}") # 10 yerine 999 yazar


DEĞİŞİM SONRASI ANA ARRAY:
[[999  20  30]
 [ 40  50  60]
 [ 70  80  90]]


In [39]:
# Eğer kopya (copy) isteniyorsa, `.copy()` metodu açıkça çağrılmalıdır
arr2d_kopya = arr2d.copy()
arr2d_kopya[0, 0] = 111 # Sadece kopyayı değiştirir
print(f"Orijinal array (değişmedi):\n{arr2d}")
print(f"Kopya array (değişti):\n{arr2d_kopya}")


Orijinal array (değişmedi):
[[999  20  30]
 [ 40  50  60]
 [ 70  80  90]]
Kopya array (değişti):
[[111  20  30]
 [ 40  50  60]
 [ 70  80  90]]


In [ ]:
# -----------------------------------------------------------------
# --- 7. FANCY INDEXING (Süslü İndeksleme) ---
# -----------------------------------------------------------------
print("\n" + "="*30 + "\n7. FANCY INDEXING\n" + "="*30)
# Bir array'den belirli index'teki elemanları (sırasız olsa bile)
# bir liste veya array kullanarak seçmek.
# Bu işlem her zaman bir KOPYA döndürür (View değil).
f_arr = np.arange(100, 110)
print(f"Fancy Array: {f_arr}")
indexler = [1, 3, 5, 0]
print(f"Seçilenler [1, 3, 5, 0]: {f_arr[indexler]}")


7. FANCY INDEXING
Fancy Array: [100 101 102 103 104 105 106 107 108 109]
Seçilenler [1, 3, 5, 0]: [101 103 105 100]


In [41]:
# 2D'de Fancy Indexing
f_arr2d = np.random.randint(10, 100, (4, 4))
print(f"\nFancy 2D Array:\n{f_arr2d}")



Fancy 2D Array:
[[99 53 43 83]
 [71 23 57 24]
 [81 87 96 71]
 [49 94 89 91]]


In [42]:
# 0. ve 2. satırları al
print(f"0. ve 2. Satırlar:\n{f_arr2d[[0, 2]]}")


0. ve 2. Satırlar:
[[99 53 43 83]
 [81 87 96 71]]


In [43]:
# (0,1), (2,3) ve (3,0) koordinatlarındaki elemanları al
print(f"Belirli koordinatlar: {f_arr2d[[0, 2, 3], [1, 3, 0]]}")


Belirli koordinatlar: [53 71 49]


In [44]:
# -----------------------------------------------------------------
# --- 8. BOOLEAN INDEXING (Koşullu Filtreleme) ---
# -----------------------------------------------------------------
print("\n" + "="*30 + "\n8. BOOLEAN INDEXING (Filtreleme)\n" + "="*30)
# Veri analizinde filtreleme için en çok kullanılan tekniktir.
b_data = np.random.randint(1, 50, (4, 5))
print(f"Filtre Verisi:\n{b_data}")




8. BOOLEAN INDEXING (Filtreleme)
Filtre Verisi:
[[47 24 26 25 45]
 [41 29 15 45  1]
 [25  7  9 24  1]
 [44  8 24 11 17]]


In [45]:
# Adım 1: Koşulu oluştur (True/False'lardan oluşan bir matris döner)
kosul = b_data > 30
print(f"Koşul (Veri > 30):\n{kosul}")


Koşul (Veri > 30):
[[ True False False False  True]
 [ True False False  True False]
 [False False False False False]
 [ True False False False False]]


In [46]:
# Adım 2: Koşulu uygula (Sadece True olanları 1D bir array olarak döndürür)
print(f"30'dan büyük elemanlar: {b_data[kosul]}")


30'dan büyük elemanlar: [47 45 41 45 44]


In [47]:
# Kısa yol (en çok kullanılan):
print(f"30'dan büyükler (kısa yol): {b_data[b_data > 30]}")


30'dan büyükler (kısa yol): [47 45 41 45 44]


In [48]:
# Çoklu Koşul: `&` (ve), `|` (veya), `~` (değil - not)
# Python'daki `and`, `or` kullanılmaz! Parantezler zorunludur!
kosul1 = b_data > 20
kosul2 = b_data < 40
print(f"20 ile 40 arasındaki elemanlar:\n{b_data[(kosul1) & (kosul2)]}")
print(f"20'den küçük VEYA 40'tan büyük elemanlar:\n{b_data[~(kosul1 & kosul2)]}") # (Değili)

20 ile 40 arasındaki elemanlar:
[24 26 25 29 25 24 24]
20'den küçük VEYA 40'tan büyük elemanlar:
[47 45 41 15 45  1  7  9  1 44  8 11 17]


In [49]:
# `np.where(koşul, doğruysa_bu, yanlışsa_bu)`
# Excel'deki IF fonksiyonu gibidir.
# 20'den büyükse 1, değilse 0 yaz
where_sonuc = np.where(b_data > 20, 1, 0)
print(f"np.where(b_data > 20, 1, 0):\n{where_sonuc}")


np.where(b_data > 20, 1, 0):
[[1 1 1 1 1]
 [1 1 0 1 0]
 [1 0 0 1 0]
 [1 0 1 0 0]]


In [50]:
# -----------------------------------------------------------------
# --- 9. VEKTÖREL OPERASYONLAR (Universal Functions - ufunc) ---
# -----------------------------------------------------------------
print("\n" + "="*30 + "\n9. VEKTÖREL OPERASYONLAR (ufunc)\n" + "="*30)
v_arr = np.arange(1, 6) # [1, 2, 3, 4, 5]

# Skaler (tekil sayı) ile işlemler (Döngüye gerek yok!)
print(f"v_arr + 100 = {v_arr + 100}")
print(f"v_arr * 3   = {v_arr * 3}")
print(f"v_arr ** 2  = {v_arr ** 2}")


9. VEKTÖREL OPERASYONLAR (ufunc)
v_arr + 100 = [101 102 103 104 105]
v_arr * 3   = [ 3  6  9 12 15]
v_arr ** 2  = [ 1  4  9 16 25]


In [51]:
# İki Array arası işlemler (Boyutlar eşleşmeli)
v_arr2 = np.ones(5) * 10 # [10, 10, 10, 10, 10]
print(f"v_arr + v_arr2 = {v_arr + v_arr2}")
print(f"v_arr / v_arr2 = {v_arr / v_arr2}")


v_arr + v_arr2 = [11. 12. 13. 14. 15.]
v_arr / v_arr2 = [0.1 0.2 0.3 0.4 0.5]


In [52]:
# Matematiksel Fonksiyonlar
print(f"Karekök: {np.sqrt(v_arr)}")
print(f"Üstel (e^x): {np.exp(v_arr)}")
print(f"Doğal Log (ln): {np.log(v_arr)}")

Karekök: [1.         1.41421356 1.73205081 2.         2.23606798]
Üstel (e^x): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Doğal Log (ln): [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [53]:
# -----------------------------------------------------------------
# --- 10. BROADCASTING (Yayınlama) ---
# -----------------------------------------------------------------
print("\n" + "="*30 + "\n10. BROADCASTING\n" + "="*30)
# NumPy'ın farklı boyutlardaki array'lerle işlem yapabilme yeteneğidir.
# Küçük olan array, büyük olanın boyutuna "yayınlanır" (genişletilir).
matris = np.ones((3, 3)) # 3x3 matris
vektor = np.array([1, 2, 3]) # 1x3 vektör

print(f"Matris:\n{matris}")
print(f"Vektör: {vektor}")


10. BROADCASTING
Matris:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Vektör: [1 2 3]


In [54]:
# Vektör [1, 2, 3], 3 satıra da kopyalanarak (yayınlanarak) toplanır
# [[1, 1, 1] + [1, 2, 3]]
# [[1, 1, 1] + [1, 2, 3]]
# [[1, 1, 1] + [1, 2, 3]]

print(f"Matris + Vektör (Broadcasting):\n{matris + vektor}")


Matris + Vektör (Broadcasting):
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [55]:
# Sütun bazlı broadcasting için vektörün shape'i (3, 1) olmalı
vektor_sutun = np.array([10, 20, 30]).reshape(3, 1)
print(f"\nSütun Vektörü:\n{vektor_sutun}")
print(f"Matris + Sütun Vektörü:\n{matris + vektor_sutun}")



Sütun Vektörü:
[[10]
 [20]
 [30]]
Matris + Sütun Vektörü:
[[11. 11. 11.]
 [21. 21. 21.]
 [31. 31. 31.]]


In [57]:
# -----------------------------------------------------------------
# --- 11. İSTATİSTİKSEL OPERASYONLAR (Aggregation) ---
# -----------------------------------------------------------------
print("\n" + "="*30 + "\n11. İSTATİSTİKSEL OPERASYONLAR\n" + "="*30)
stats_data = np.random.randint(1, 100, 10)
print(f"İstatistik Verisi: {stats_data}")

print(f"Toplam (sum): {stats_data.sum()}")
print(f"Ortalama (mean): {stats_data.mean()}")
print(f"Standart Sapma (std): {stats_data.std()}")
print(f"Varyans (var): {stats_data.var()}")
print(f"Minimum (min): {stats_data.min()}")
print(f"Maksimum (max): {stats_data.max()}")


11. İSTATİSTİKSEL OPERASYONLAR
İstatistik Verisi: [12 34 33 48 23 62 88 37 99 44]
Toplam (sum): 480
Ortalama (mean): 48.0
Standart Sapma (std): 26.22212806009459
Varyans (var): 687.6
Minimum (min): 12
Maksimum (max): 99


In [58]:
# `.argmin()` ve `.argmax()`: Min/Max değerlerin index'ini verir
print(f"Minimum değerin index'i (argmin): {stats_data.argmin()}")
print(f"Maksimum değerin index'i (argmax): {stats_data.argmax()}")

# Kümülatif (Birikimli) Toplam/Çarpım
print(f"Kümülatif Toplam (cumsum): {stats_data.cumsum()}")

Minimum değerin index'i (argmin): 0
Maksimum değerin index'i (argmax): 8
Kümülatif Toplam (cumsum): [ 12  46  79 127 150 212 300 337 436 480]


In [59]:
# -----------------------------------------------------------------
# --- 12. `axis` PARAMETRESİ (Satır/Sütun Bazlı İşlemler) ---
# -----------------------------------------------------------------

print("\n" + "="*30 + "\n12. 'axis' PARAMETRESİ\n" + "="*30)
# NumPy'da en kritik konseptlerden biri.
# `axis=0` -> Sütunlar boyunca (dikey) işlem. (Satırları 'çöktürür')
# `axis=1` -> Satırlar boyunca (yatay) işlem. (Sütunları 'çöktürür')

axis_matris = np.array([[1, 2, 3], [10, 20, 30]])
print(f"Axis Matrisi:\n{axis_matris}")



12. 'axis' PARAMETRESİ
Axis Matrisi:
[[ 1  2  3]
 [10 20 30]]


In [60]:
# Sütunların toplamı (axis=0) -> [1+10, 2+20, 3+30]
print(f"Sütun Toplamları (axis=0): {axis_matris.sum(axis=0)}")


Sütun Toplamları (axis=0): [11 22 33]


In [61]:
# Satırların toplamı (axis=1) -> [1+2+3, 10+20+30]
print(f"Satır Toplamları (axis=1): {axis_matris.sum(axis=1)}")


Satır Toplamları (axis=1): [ 6 60]


In [62]:
# Sütunların ortalaması (axis=0)
print(f"Sütun Ortalamaları (axis=0): {axis_matris.mean(axis=0)}")


Sütun Ortalamaları (axis=0): [ 5.5 11.  16.5]


In [63]:
# -----------------------------------------------------------------
# --- 13. MATEMATİKSEL İŞLEMLER VE LİNEER CEBİR ---
# -----------------------------------------------------------------
print("\n" + "="*30 + "\n13. LİNEER CEBİR\n" + "="*30)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise çarpma (Hadamard Product)
print(f"Element-wise Çarpma (A * B):\n{A * B}")




13. LİNEER CEBİR
Element-wise Çarpma (A * B):
[[ 5 12]
 [21 32]]


In [64]:
# Matris Çarpımı (Dot Product)
# Yöntem 1: `.dot()`
print(f"Matris Çarpımı (A.dot(B)):\n{A.dot(B)}")
# Yöntem 2: `@` operatörü (Python 3.5+)
print(f"Matris Çarpımı (A @ B):\n{A @ B}")


Matris Çarpımı (A.dot(B)):
[[19 22]
 [43 50]]
Matris Çarpımı (A @ B):
[[19 22]
 [43 50]]


In [65]:
# Transpoze (Satır ve sütunların yerini değiştirme)
print(f"A'nın Transpozesi (A.T):\n{A.T}")


A'nın Transpozesi (A.T):
[[1 3]
 [2 4]]


In [66]:
# Determinant
print(f"A'nın Determinantı: {np.linalg.det(A)}")


A'nın Determinantı: -2.0000000000000004


In [67]:
# Ters (Inverse)
print(f"A'nın Tersi (Inverse):\n{np.linalg.inv(A)}")


A'nın Tersi (Inverse):
[[-2.   1. ]
 [ 1.5 -0.5]]


In [72]:
# -----------------------------------------------------------------
# --- 14. ARRAY BİRLEŞTİRME VE PARÇALAMA ---
# -----------------------------------------------------------------
print("\n" + "="*30 + "\n14. ARRAY BİRLEŞTİRME VE PARÇALAMA\n" + "="*30)

# --- 14.1. Birleştirme ---
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Dikey Birleştirme (Alt alta)
# `np.concatenate` (axis=0 ile)
print(f"Concatenate (axis=0):\n{np.concatenate((a, b), axis=0)}")

# veya `np.vstack` (Vertical Stack)
print(f"vstack:\n{np.vstack((a, b))}")


14. ARRAY BİRLEŞTİRME VE PARÇALAMA
Concatenate (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [73]:


# Yatay Birleştirme (Yan yana)
# `np.concatenate` (axis=1 ile)
print(f"Concatenate (axis=1):\n{np.concatenate((a, b), axis=1)}")
# veya `np.hstack` (Horizontal Stack)
print(f"hstack:\n{np.hstack((a, b))}")

Concatenate (axis=1):
[[1 2 5 6]
 [3 4 7 8]]
hstack:
[[1 2 5 6]
 [3 4 7 8]]


In [74]:
# --- 14.2. Parçalama (Splitting) ---
c = np.arange(1, 10) # [1, 2, ..., 9]
print(f"\nParçalanacak Array: {c}")



Parçalanacak Array: [1 2 3 4 5 6 7 8 9]


In [75]:
# 3 eşit parçaya böl
print(f"3 eşit parçaya böl: {np.split(c, 3)}")


3 eşit parçaya böl: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [76]:
# Belirli noktalardan böl (2. ve 5. index'ten)
print(f"Belirli noktalardan böl: {np.split(c, [2, 5])}")


Belirli noktalardan böl: [array([1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]


In [78]:
# `vsplit` (dikey) ve `hsplit` (yatay) matrisler için kullanılır
d = np.arange(16).reshape(4, 4)
print(f"\nParçalanacak Matris:\n{d}")


Parçalanacak Matris:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [79]:
print(f"vsplit (2 eşit parçaya):\n{np.vsplit(d, 2)}")

vsplit (2 eşit parçaya):
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [80]:

print(f"hsplit (2 eşit parçaya):\n{np.hsplit(d, 2)}")

hsplit (2 eşit parçaya):
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
